// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carla.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_carla_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_carla_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_carla_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_carla_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_carla_2eproto;
namespace carla {
class EmptyRequest;
class EmptyRequestDefaultTypeInternal;
extern EmptyRequestDefaultTypeInternal _EmptyRequest_default_instance_;
class SensorData;
class SensorDataDefaultTypeInternal;
extern SensorDataDefaultTypeInternal _SensorData_default_instance_;
}  // namespace carla
PROTOBUF_NAMESPACE_OPEN
template<> ::carla::EmptyRequest* Arena::CreateMaybeMessage<::carla::EmptyRequest>(Arena*);
template<> ::carla::SensorData* Arena::CreateMaybeMessage<::carla::SensorData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace carla {

// ===================================================================

class EmptyRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:carla.EmptyRequest) */ {
 public:
  inline EmptyRequest() : EmptyRequest(nullptr) {};
  virtual ~EmptyRequest();

  EmptyRequest(const EmptyRequest& from);
  EmptyRequest(EmptyRequest&& from) noexcept
    : EmptyRequest() {
    *this = ::std::move(from);
  }

  inline EmptyRequest& operator=(const EmptyRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline EmptyRequest& operator=(EmptyRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EmptyRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EmptyRequest* internal_default_instance() {
    return reinterpret_cast<const EmptyRequest*>(
               &_EmptyRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(EmptyRequest& a, EmptyRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(EmptyRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EmptyRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EmptyRequest* New() const final {
    return CreateMaybeMessage<EmptyRequest>(nullptr);
  }

  EmptyRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EmptyRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EmptyRequest& from);
  void MergeFrom(const EmptyRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EmptyRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "carla.EmptyRequest";
  }
  protected:
  explicit EmptyRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_carla_2eproto);
    return ::descriptor_table_carla_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:carla.EmptyRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_carla_2eproto;
};
// -------------------------------------------------------------------

class SensorData PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:carla.SensorData) */ {
 public:
  inline SensorData() : SensorData(nullptr) {};
  virtual ~SensorData();

  SensorData(const SensorData& from);
  SensorData(SensorData&& from) noexcept
    : SensorData() {
    *this = ::std::move(from);
  }

  inline SensorData& operator=(const SensorData& from) {
    CopyFrom(from);
    return *this;
  }
  inline SensorData& operator=(SensorData&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SensorData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SensorData* internal_default_instance() {
    return reinterpret_cast<const SensorData*>(
               &_SensorData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SensorData& a, SensorData& b) {
    a.Swap(&b);
  }
  inline void Swap(SensorData* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SensorData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SensorData* New() const final {
    return CreateMaybeMessage<SensorData>(nullptr);
  }

  SensorData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SensorData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SensorData& from);
  void MergeFrom(const SensorData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SensorData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "carla.SensorData";
  }
  protected:
  explicit SensorData(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_carla_2eproto);
    return ::descriptor_table_carla_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTrafficSignFieldNumber = 7,
    kStatusFieldNumber = 8,
    kSpeedFieldNumber = 1,
    kAccelerationFieldNumber = 2,
    kSteeringFieldNumber = 3,
    kBrakeFieldNumber = 4,
    kThrottleFieldNumber = 5,
    kLaneOffsetFieldNumber = 6,
  };
  // string traffic_sign = 7;
  void clear_traffic_sign();
  const std::string& traffic_sign() const;
  void set_traffic_sign(const std::string& value);
  void set_traffic_sign(std::string&& value);
  void set_traffic_sign(const char* value);
  void set_traffic_sign(const char* value, size_t size);
  std::string* mutable_traffic_sign();
  std::string* release_traffic_sign();
  void set_allocated_traffic_sign(std::string* traffic_sign);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_traffic_sign();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_traffic_sign(
      std::string* traffic_sign);
  private:
  const std::string& _internal_traffic_sign() const;
  void _internal_set_traffic_sign(const std::string& value);
  std::string* _internal_mutable_traffic_sign();
  public:

  // string status = 8;
  void clear_status();
  const std::string& status() const;
  void set_status(const std::string& value);
  void set_status(std::string&& value);
  void set_status(const char* value);
  void set_status(const char* value, size_t size);
  std::string* mutable_status();
  std::string* release_status();
  void set_allocated_status(std::string* status);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_status();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_status(
      std::string* status);
  private:
  const std::string& _internal_status() const;
  void _internal_set_status(const std::string& value);
  std::string* _internal_mutable_status();
  public:

  // float speed = 1;
  void clear_speed();
  float speed() const;
  void set_speed(float value);
  private:
  float _internal_speed() const;
  void _internal_set_speed(float value);
  public:

  // float acceleration = 2;
  void clear_acceleration();
  float acceleration() const;
  void set_acceleration(float value);
  private:
  float _internal_acceleration() const;
  void _internal_set_acceleration(float value);
  public:

  // float steering = 3;
  void clear_steering();
  float steering() const;
  void set_steering(float value);
  private:
  float _internal_steering() const;
  void _internal_set_steering(float value);
  public:

  // float brake = 4;
  void clear_brake();
  float brake() const;
  void set_brake(float value);
  private:
  float _internal_brake() const;
  void _internal_set_brake(float value);
  public:

  // float throttle = 5;
  void clear_throttle();
  float throttle() const;
  void set_throttle(float value);
  private:
  float _internal_throttle() const;
  void _internal_set_throttle(float value);
  public:

  // float lane_offset = 6;
  void clear_lane_offset();
  float lane_offset() const;
  void set_lane_offset(float value);
  private:
  float _internal_lane_offset() const;
  void _internal_set_lane_offset(float value);
  public:

  // @@protoc_insertion_point(class_scope:carla.SensorData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr traffic_sign_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr status_;
  float speed_;
  float acceleration_;
  float steering_;
  float brake_;
  float throttle_;
  float lane_offset_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_carla_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EmptyRequest

// -------------------------------------------------------------------

// SensorData

// float speed = 1;
inline void SensorData::clear_speed() {
  speed_ = 0;
}
inline float SensorData::_internal_speed() const {
  return speed_;
}
inline float SensorData::speed() const {
  // @@protoc_insertion_point(field_get:carla.SensorData.speed)
  return _internal_speed();
}
inline void SensorData::_internal_set_speed(float value) {
  
  speed_ = value;
}
inline void SensorData::set_speed(float value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:carla.SensorData.speed)
}

// float acceleration = 2;
inline void SensorData::clear_acceleration() {
  acceleration_ = 0;
}
inline float SensorData::_internal_acceleration() const {
  return acceleration_;
}
inline float SensorData::acceleration() const {
  // @@protoc_insertion_point(field_get:carla.SensorData.acceleration)
  return _internal_acceleration();
}
inline void SensorData::_internal_set_acceleration(float value) {
  
  acceleration_ = value;
}
inline void SensorData::set_acceleration(float value) {
  _internal_set_acceleration(value);
  // @@protoc_insertion_point(field_set:carla.SensorData.acceleration)
}

// float steering = 3;
inline void SensorData::clear_steering() {
  steering_ = 0;
}
inline float SensorData::_internal_steering() const {
  return steering_;
}
inline float SensorData::steering() const {
  // @@protoc_insertion_point(field_get:carla.SensorData.steering)
  return _internal_steering();
}
inline void SensorData::_internal_set_steering(float value) {
  
  steering_ = value;
}
inline void SensorData::set_steering(float value) {
  _internal_set_steering(value);
  // @@protoc_insertion_point(field_set:carla.SensorData.steering)
}

// float brake = 4;
inline void SensorData::clear_brake() {
  brake_ = 0;
}
inline float SensorData::_internal_brake() const {
  return brake_;
}
inline float SensorData::brake() const {
  // @@protoc_insertion_point(field_get:carla.SensorData.brake)
  return _internal_brake();
}
inline void SensorData::_internal_set_brake(float value) {
  
  brake_ = value;
}
inline void SensorData::set_brake(float value) {
  _internal_set_brake(value);
  // @@protoc_insertion_point(field_set:carla.SensorData.brake)
}

// float throttle = 5;
inline void SensorData::clear_throttle() {
  throttle_ = 0;
}
inline float SensorData::_internal_throttle() const {
  return throttle_;
}
inline float SensorData::throttle() const {
  // @@protoc_insertion_point(field_get:carla.SensorData.throttle)
  return _internal_throttle();
}
inline void SensorData::_internal_set_throttle(float value) {
  
  throttle_ = value;
}
inline void SensorData::set_throttle(float value) {
  _internal_set_throttle(value);
  // @@protoc_insertion_point(field_set:carla.SensorData.throttle)
}

// float lane_offset = 6;
inline void SensorData::clear_lane_offset() {
  lane_offset_ = 0;
}
inline float SensorData::_internal_lane_offset() const {
  return lane_offset_;
}
inline float SensorData::lane_offset() const {
  // @@protoc_insertion_point(field_get:carla.SensorData.lane_offset)
  return _internal_lane_offset();
}
inline void SensorData::_internal_set_lane_offset(float value) {
  
  lane_offset_ = value;
}
inline void SensorData::set_lane_offset(float value) {
  _internal_set_lane_offset(value);
  // @@protoc_insertion_point(field_set:carla.SensorData.lane_offset)
}

// string traffic_sign = 7;
inline void SensorData::clear_traffic_sign() {
  traffic_sign_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& SensorData::traffic_sign() const {
  // @@protoc_insertion_point(field_get:carla.SensorData.traffic_sign)
  return _internal_traffic_sign();
}
inline void SensorData::set_traffic_sign(const std::string& value) {
  _internal_set_traffic_sign(value);
  // @@protoc_insertion_point(field_set:carla.SensorData.traffic_sign)
}
inline std::string* SensorData::mutable_traffic_sign() {
  // @@protoc_insertion_point(field_mutable:carla.SensorData.traffic_sign)
  return _internal_mutable_traffic_sign();
}
inline const std::string& SensorData::_internal_traffic_sign() const {
  return traffic_sign_.Get();
}
inline void SensorData::_internal_set_traffic_sign(const std::string& value) {
  
  traffic_sign_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void SensorData::set_traffic_sign(std::string&& value) {
  
  traffic_sign_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:carla.SensorData.traffic_sign)
}
inline void SensorData::set_traffic_sign(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  traffic_sign_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:carla.SensorData.traffic_sign)
}
inline void SensorData::set_traffic_sign(const char* value,
    size_t size) {
  
  traffic_sign_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:carla.SensorData.traffic_sign)
}
inline std::string* SensorData::_internal_mutable_traffic_sign() {
  
  return traffic_sign_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* SensorData::release_traffic_sign() {
  // @@protoc_insertion_point(field_release:carla.SensorData.traffic_sign)
  return traffic_sign_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SensorData::set_allocated_traffic_sign(std::string* traffic_sign) {
  if (traffic_sign != nullptr) {
    
  } else {
    
  }
  traffic_sign_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), traffic_sign,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:carla.SensorData.traffic_sign)
}
inline std::string* SensorData::unsafe_arena_release_traffic_sign() {
  // @@protoc_insertion_point(field_unsafe_arena_release:carla.SensorData.traffic_sign)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return traffic_sign_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void SensorData::unsafe_arena_set_allocated_traffic_sign(
    std::string* traffic_sign) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (traffic_sign != nullptr) {
    
  } else {
    
  }
  traffic_sign_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      traffic_sign, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:carla.SensorData.traffic_sign)
}

// string status = 8;
inline void SensorData::clear_status() {
  status_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& SensorData::status() const {
  // @@protoc_insertion_point(field_get:carla.SensorData.status)
  return _internal_status();
}
inline void SensorData::set_status(const std::string& value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:carla.SensorData.status)
}
inline std::string* SensorData::mutable_status() {
  // @@protoc_insertion_point(field_mutable:carla.SensorData.status)
  return _internal_mutable_status();
}
inline const std::string& SensorData::_internal_status() const {
  return status_.Get();
}
inline void SensorData::_internal_set_status(const std::string& value) {
  
  status_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void SensorData::set_status(std::string&& value) {
  
  status_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:carla.SensorData.status)
}
inline void SensorData::set_status(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  status_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:carla.SensorData.status)
}
inline void SensorData::set_status(const char* value,
    size_t size) {
  
  status_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:carla.SensorData.status)
}
inline std::string* SensorData::_internal_mutable_status() {
  
  return status_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* SensorData::release_status() {
  // @@protoc_insertion_point(field_release:carla.SensorData.status)
  return status_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SensorData::set_allocated_status(std::string* status) {
  if (status != nullptr) {
    
  } else {
    
  }
  status_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), status,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:carla.SensorData.status)
}
inline std::string* SensorData::unsafe_arena_release_status() {
  // @@protoc_insertion_point(field_unsafe_arena_release:carla.SensorData.status)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return status_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void SensorData::unsafe_arena_set_allocated_status(
    std::string* status) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (status != nullptr) {
    
  } else {
    
  }
  status_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      status, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:carla.SensorData.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace carla

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_carla_2eproto
