// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: carla.proto

#include "carla.pb.h"
#include "carla.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace carla {

static const char* CarlaDataService_method_names[] = {
  "/carla.CarlaDataService/GetSensorData",
};

std::unique_ptr< CarlaDataService::Stub> CarlaDataService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CarlaDataService::Stub> stub(new CarlaDataService::Stub(channel));
  return stub;
}

CarlaDataService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetSensorData_(CarlaDataService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CarlaDataService::Stub::GetSensorData(::grpc::ClientContext* context, const ::carla::EmptyRequest& request, ::carla::SensorResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetSensorData_, context, request, response);
}

void CarlaDataService::Stub::experimental_async::GetSensorData(::grpc::ClientContext* context, const ::carla::EmptyRequest* request, ::carla::SensorResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetSensorData_, context, request, response, std::move(f));
}

void CarlaDataService::Stub::experimental_async::GetSensorData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::carla::SensorResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetSensorData_, context, request, response, std::move(f));
}

void CarlaDataService::Stub::experimental_async::GetSensorData(::grpc::ClientContext* context, const ::carla::EmptyRequest* request, ::carla::SensorResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetSensorData_, context, request, response, reactor);
}

void CarlaDataService::Stub::experimental_async::GetSensorData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::carla::SensorResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetSensorData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::carla::SensorResponse>* CarlaDataService::Stub::AsyncGetSensorDataRaw(::grpc::ClientContext* context, const ::carla::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::carla::SensorResponse>::Create(channel_.get(), cq, rpcmethod_GetSensorData_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::carla::SensorResponse>* CarlaDataService::Stub::PrepareAsyncGetSensorDataRaw(::grpc::ClientContext* context, const ::carla::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::carla::SensorResponse>::Create(channel_.get(), cq, rpcmethod_GetSensorData_, context, request, false);
}

CarlaDataService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CarlaDataService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CarlaDataService::Service, ::carla::EmptyRequest, ::carla::SensorResponse>(
          [](CarlaDataService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::carla::EmptyRequest* req,
             ::carla::SensorResponse* resp) {
               return service->GetSensorData(ctx, req, resp);
             }, this)));
}

CarlaDataService::Service::~Service() {
}

::grpc::Status CarlaDataService::Service::GetSensorData(::grpc::ServerContext* context, const ::carla::EmptyRequest* request, ::carla::SensorResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace carla

