// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: carla.proto
#ifndef GRPC_carla_2eproto__INCLUDED
#define GRPC_carla_2eproto__INCLUDED

#include "carla.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace carla {

class CarlaDataService final {
 public:
  static constexpr char const* service_full_name() {
    return "carla.CarlaDataService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetSensorData(::grpc::ClientContext* context, const ::carla::EmptyRequest& request, ::carla::SensorResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::carla::SensorResponse>> AsyncGetSensorData(::grpc::ClientContext* context, const ::carla::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::carla::SensorResponse>>(AsyncGetSensorDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::carla::SensorResponse>> PrepareAsyncGetSensorData(::grpc::ClientContext* context, const ::carla::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::carla::SensorResponse>>(PrepareAsyncGetSensorDataRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetSensorData(::grpc::ClientContext* context, const ::carla::EmptyRequest* request, ::carla::SensorResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetSensorData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::carla::SensorResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetSensorData(::grpc::ClientContext* context, const ::carla::EmptyRequest* request, ::carla::SensorResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetSensorData(::grpc::ClientContext* context, const ::carla::EmptyRequest* request, ::carla::SensorResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetSensorData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::carla::SensorResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetSensorData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::carla::SensorResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::carla::SensorResponse>* AsyncGetSensorDataRaw(::grpc::ClientContext* context, const ::carla::EmptyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::carla::SensorResponse>* PrepareAsyncGetSensorDataRaw(::grpc::ClientContext* context, const ::carla::EmptyRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetSensorData(::grpc::ClientContext* context, const ::carla::EmptyRequest& request, ::carla::SensorResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::carla::SensorResponse>> AsyncGetSensorData(::grpc::ClientContext* context, const ::carla::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::carla::SensorResponse>>(AsyncGetSensorDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::carla::SensorResponse>> PrepareAsyncGetSensorData(::grpc::ClientContext* context, const ::carla::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::carla::SensorResponse>>(PrepareAsyncGetSensorDataRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetSensorData(::grpc::ClientContext* context, const ::carla::EmptyRequest* request, ::carla::SensorResponse* response, std::function<void(::grpc::Status)>) override;
      void GetSensorData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::carla::SensorResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetSensorData(::grpc::ClientContext* context, const ::carla::EmptyRequest* request, ::carla::SensorResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetSensorData(::grpc::ClientContext* context, const ::carla::EmptyRequest* request, ::carla::SensorResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetSensorData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::carla::SensorResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetSensorData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::carla::SensorResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::carla::SensorResponse>* AsyncGetSensorDataRaw(::grpc::ClientContext* context, const ::carla::EmptyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::carla::SensorResponse>* PrepareAsyncGetSensorDataRaw(::grpc::ClientContext* context, const ::carla::EmptyRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetSensorData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetSensorData(::grpc::ServerContext* context, const ::carla::EmptyRequest* request, ::carla::SensorResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetSensorData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetSensorData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetSensorData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSensorData(::grpc::ServerContext* /*context*/, const ::carla::EmptyRequest* /*request*/, ::carla::SensorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSensorData(::grpc::ServerContext* context, ::carla::EmptyRequest* request, ::grpc::ServerAsyncResponseWriter< ::carla::SensorResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetSensorData<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetSensorData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetSensorData() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::carla::EmptyRequest, ::carla::SensorResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::carla::EmptyRequest* request, ::carla::SensorResponse* response) { return this->GetSensorData(context, request, response); }));}
    void SetMessageAllocatorFor_GetSensorData(
        ::grpc::experimental::MessageAllocator< ::carla::EmptyRequest, ::carla::SensorResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::carla::EmptyRequest, ::carla::SensorResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetSensorData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSensorData(::grpc::ServerContext* /*context*/, const ::carla::EmptyRequest* /*request*/, ::carla::SensorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetSensorData(
      ::grpc::CallbackServerContext* /*context*/, const ::carla::EmptyRequest* /*request*/, ::carla::SensorResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetSensorData(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::carla::EmptyRequest* /*request*/, ::carla::SensorResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_GetSensorData<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_GetSensorData<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetSensorData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetSensorData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetSensorData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSensorData(::grpc::ServerContext* /*context*/, const ::carla::EmptyRequest* /*request*/, ::carla::SensorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetSensorData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetSensorData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetSensorData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSensorData(::grpc::ServerContext* /*context*/, const ::carla::EmptyRequest* /*request*/, ::carla::SensorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSensorData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetSensorData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetSensorData() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetSensorData(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetSensorData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSensorData(::grpc::ServerContext* /*context*/, const ::carla::EmptyRequest* /*request*/, ::carla::SensorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetSensorData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetSensorData(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetSensorData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetSensorData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::carla::EmptyRequest, ::carla::SensorResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::carla::EmptyRequest, ::carla::SensorResponse>* streamer) {
                       return this->StreamedGetSensorData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetSensorData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetSensorData(::grpc::ServerContext* /*context*/, const ::carla::EmptyRequest* /*request*/, ::carla::SensorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetSensorData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::carla::EmptyRequest,::carla::SensorResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetSensorData<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetSensorData<Service > StreamedService;
};

}  // namespace carla


#endif  // GRPC_carla_2eproto__INCLUDED
